# Triggered once.

name: 05 - Create the BE application environment

on:
  workflow_dispatch:
    inputs:
      environmentName:
        description: 'The name of the environment in which to deploy the app-specific environment resources.'
        required: true
        default: 'staging'
      applicationName:
        description: 'The name of the application for which to set-up the environment.'
        required: true
        default: 'core'
jobs:
  deploy-database-stack:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    name: Deploy the database stack

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Install CDK
        run: |
          npm i -g aws-cdk
          echo "CKD version:"
          cdk version

      - name: NPM install
        run: npm i

      - name: Deploy database stack
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEPLOY_REGION }}
        run: |
          npm run database:deploy -- \
            -c environmentName=${{ github.event.inputs.environmentName }} \
            -c applicationName=${{ github.event.inputs.applicationName }} \
            -c accountId=${{ secrets.AWS_ACCOUNT_ID }} \
            -c region=${{ secrets.AWS_DEPLOY_REGION }}
